export const demo_app = {
  idapp: "c4ca4238a0b923820dcc509a6f75849b",
  app: "demo",
  enabled: true,
  vars: {
    dev: {
      $_VAR_DEMO_1: 10,
      $_VAR_DEMO_2: {
        host: "google.com",
        var1: {
          a: 10,
          b: {
            casti: 3,
          },
        },
      },
      $_VAR_FETCH: "https://fakestoreapi.com/carts",
      $_VAR_SQLITE: {
        database: "memory",
        username: "",
        password: "",
        options: {
          host: "localhost",
          dialect: "sqlite",
        },
      },
      $_VAR_SOAP_TEST: {
        wsdl: "https://www.dataaccess.com/webservicesserver/numberconversion.wso?WSDL",
        functionName: "NumberToDollars",
        BasicAuthSecurity: {
          User: "any",
          Password: "any",
        },
      },
    },
    qa: {
      $_VAR_DEMO_1: 10,
      $_VAR_DEMO_2: {
        host: "google.com",
        var1: {
          a: 10,
          b: {
            casti: 3,
          },
        },
      },
      $_VAR_FETCH: "https://fakestoreapi.com/carts",
      $_VAR_SQLITE: {
        database: "memory",
        username: "",
        password: "",
        options: {
          host: "localhost",
          dialect: "sqlite",
        },
      },
      $_VAR_SOAP_TEST: {
        wsdl: "https://www.dataaccess.com/webservicesserver/numberconversion.wso?WSDL",
        functionName: "NumberToDollars",
        BasicAuthSecurity: {
          User: "any",
          Password: "any",
        },
      },
    },
    prd: {
      $_VAR_DEMO_1: 10,
      $_VAR_DEMO_2: {
        host: "google.com",
        var1: {
          a: 10,
          b: {
            casti: 3,
          },
        },
      },
      $_VAR_FETCH: "https://fakestoreapi.com/carts",
      $_VAR_SQLITE: {
        database: "memory",
        username: "",
        password: "",
        options: {
          host: "localhost",
          dialect: "sqlite",
        },
      },
      $_VAR_SOAP_TEST: {
        wsdl: "https://www.dataaccess.com/webservicesserver/numberconversion.wso?WSDL",
        functionName: "NumberToDollars",
        BasicAuthSecurity: {
          User: "any",
          Password: "any",
        },
      },
    },
  },
  description: "App DEMO",
  rowkey: 0,
  endpoints: [
    {
      endpoint: "/api/demo/main/test_fetch/0.01/dev",
      idendpoint: "316e671e-bda5-42d3-9c7b-4984bc79e5b6",
      enabled: true,
      access: 0,
      ctrl: null,
      environment: "dev",
      resource: "/main/test_fetch/0.01",
      method: "GET",
      handler: "FETCH",
      cors: null,
      code: "https://api.github.com/users/edwinspire",
      description: "",
      headers_test: {},
      data_test: {},
      rowkey: 327,
      latest_updater: null,
      cache_time: 0,
      internal_hash_row:
        "5dc1b22318410b6e37bec9c22f1c001446e9e79e47f88e6af42b038265fbf81e",
    },
    {
      endpoint: "/ws/demo/main/test_fetch/0.01/dev",
      idendpoint: "04008715-90ac-4add-8bba-139d3232367a",
      enabled: true,
      access: 0,
      ctrl: null,
      environment: "dev",
      resource: "/main/test_fetch/0.01",
      method: "WS",
      handler: "NA",
      cors: null,
      code: "https://api.github.com/users/edwinspire",
      description: "",
      headers_test: {},
      data_test: {},
      rowkey: 688,
      latest_updater: null,
      cache_time: 0,
      internal_hash_row:
        "06c341f18506ed316ac33e0ac211f5e44866edf2d2b77c8cbd24c2a776b66e75",
    },
    {
      endpoint: "/api/demo/main/test_fetch/0.02/dev",
      idendpoint: "68878fcd-4783-4b5b-8b99-a7c10f502aa8",
      enabled: true,
      access: 0,
      ctrl: null,
      environment: "dev",
      resource: "/main/test_fetch/0.02",
      method: "GET",
      handler: "FETCH",
      cors: null,
      code: "$_VAR_FETCH",
      description: "",
      headers_test: {},
      data_test: {},
      rowkey: 648,
      latest_updater: null,
      cache_time: 0,
      internal_hash_row:
        "6b2d15b64e38a5db8144cdeb22dce5cb916a5d5254bf9e8a1063cf9b794a13ee",
    },
    {
      endpoint: "/api/demo/main/test_functions/0.01/dev",
      idendpoint: "3adc4de9-9d81-4f9d-bc80-0a962f00bc84",
      enabled: true,
      access: 0,
      ctrl: null,
      environment: "dev",
      resource: "/main/test_functions/0.01",
      method: "GET",
      handler: "FUNCTION",
      cors: null,
      code: "fnPublicAdd",
      description: "",
      headers_test: {},
      data_test: {},
      rowkey: 633,
      latest_updater: null,
      cache_time: 0,
      internal_hash_row:
        "06ad7bb17f225dff6c6ac2366fa6c784705aa045d854d1728d5b423919069304",
    },
    {
      endpoint: "/api/demo/main/test_functions/0.01/dev",
      idendpoint: "f12774e0-3d3b-4b08-b849-a778802c3f7d",
      enabled: true,
      access: 0,
      ctrl: null,
      environment: "dev",
      resource: "/main/test_functions/0.01",
      method: "POST",
      handler: "FUNCTION",
      cors: null,
      code: "fnPublicDemo",
      description: "",
      headers_test: {},
      data_test: {},
      rowkey: 479,
      latest_updater: null,
      cache_time: 0,
      internal_hash_row:
        "3605cb6208b12bc6e7f341781b652e19bdacb71828fe959d08255faa95db508e",
    },
    {
      endpoint: "/api/demo/main/test_javascript/0.01/dev",
      idendpoint: "c82a0fbd-4f37-4ccb-9aac-eaa7ae056cd4",
      enabled: true,
      access: 0,
      ctrl: null,
      environment: "dev",
      resource: "/main/test_javascript/0.01",
      method: "GET",
      handler: "JS",
      cors: null,
      code: "$_RETURN_DATA_ = {name: $_REQUEST_.query.name};",
      description: "",
      headers_test: {},
      data_test: {},
      rowkey: 457,
      latest_updater: null,
      cache_time: 0,
      internal_hash_row:
        "928bc0ee1181832588324f0cb2fc41aa776c746a3ed524a20d9edb22f3941906",
    },
    {
      endpoint: "/api/demo/main/test_javascript/0.02/dev",
      idendpoint: "19a376bf-9d65-47dc-a65e-16347fe466cd",
      enabled: true,
      access: 3,
      ctrl: {
        demo: true,
      },
      environment: "dev",
      resource: "/main/test_javascript/0.02",
      method: "GET",
      handler: "JS",
      cors: null,
      code: "$_RETURN_DATA_ = $_VARS_APP;",
      description: "",
      headers_test: {},
      data_test: {},
      rowkey: 699,
      latest_updater: null,
      cache_time: 0,
      internal_hash_row:
        "8432a6630b8b35e1b985b280ccee910ace74e174c05442c9978d0766afcc280c",
    },
    {
      endpoint: "/api/demo/main/test_javascript/array_objects/0.01/dev",
      idendpoint: "4ca1db7f-8ed8-4fc1-a849-03081f7f9d2d",
      enabled: true,
      access: 0,
      ctrl: null,
      environment: "dev",
      resource: "/main/test_javascript/array_objects/0.01",
      method: "GET",
      handler: "JS",
      cors: null,
      code: "$_RETURN_DATA_ = [];\n\nwhile ($_RETURN_DATA_.length < 30) {\n  const objeto = { value1: Math.floor(Math.random() * 1000), value2: Math.floor(Math.random() * 1000) };\n  $_RETURN_DATA_.push(objeto);\n}\n",
      description: "",
      headers_test: {},
      data_test: {},
      rowkey: 919,
      latest_updater: null,
      cache_time: 0,
      internal_hash_row:
        "2ac0e01d2f55672831a9f150186cce181ea97f58f03a7d0fe48ac312626721d7",
    },
    {
      endpoint: "/api/demo/main/test_javascript/fetch/0.01/dev",
      idendpoint: "d28e93ae-0288-4eaf-9d94-9473a40d84fa",
      enabled: true,
      access: 0,
      ctrl: null,
      environment: "dev",
      resource: "/main/test_javascript/fetch/0.01",
      method: "GET",
      handler: "JS",
      cors: null,
      code: "let uf = new $_UFETCH_();\nlet r1 = await uf.get('http://localhost:3000/api/demo/main/test_javascript_return_array_objects/v0.01/dev');\n\n$_RETURN_DATA_ = await r1.json();\n",
      description: "",
      headers_test: {},
      data_test: {},
      rowkey: 652,
      latest_updater: null,
      cache_time: 0,
      internal_hash_row:
        "2a75217a2e5dd16c3152eb264c1319bdb9b047eeb5e121861f04a21e0ad6dfd8",
    },
    {
      endpoint: "/api/demo/main/test_javascript/two_fetch_ByBlocks/0.01/dev",
      idendpoint: "25e79860-f3a3-47eb-b52a-5614290a7c7e",
      enabled: true,
      access: 0,
      ctrl: null,
      environment: "dev",
      resource: "/main/test_javascript/two_fetch_ByBlocks/0.01",
      method: "GET",
      handler: "JS",
      cors: null,
      code: "let uf = new $_UFETCH_();\n// First fetch\nlet r1 = await uf.get('http://localhost:3000/api/demo/main/test_javascript_return_array_objects/v0.01/dev');\nlet r1j = await r1.json();\n\n// Second fetch with Secuential Promise\nlet rblock = await $_SECUENTIAL_PROMISES_.ByBlocks(async(data)=>{\nlet val = data.value1+data.value2; \n\nlet r2 = await uf.get('http://localhost:3000/api/demo/main/test_soap/v0.01/dev', {dNum: val});\nlet r2j = await r2.json();\n  \n  return r2j;  \n}, r1j, 2);\n\n\n\n$_RETURN_DATA_ = await rblock;\n",
      description: "",
      headers_test: {},
      data_test: {},
      rowkey: 623,
      latest_updater: null,
      cache_time: 0,
      internal_hash_row:
        "55cd2bed87ded15af98091be759dd40e1387bd5cdaaf6c1b97835e49fbe423da",
    },
    {
      endpoint: "/api/demo/main/test_soap/0.01/dev",
      idendpoint: "89859bec-db89-4e1a-bbfa-a5dd1e38b5ed",
      enabled: true,
      access: 0,
      ctrl: null,
      environment: "dev",
      resource: "/main/test_soap/0.01",
      method: "GET",
      handler: "SOAP",
      cors: null,
      code: '{\n  "wsdl": "https://www.dataaccess.com/webservicesserver/numberconversion.wso?WSDL",\n  "functionName": "NumberToDollars",\n  "BasicAuthSecurity": {\n    "User": "any",\n    "Password": "any"\n  }\n}',
      description: "",
      headers_test: {},
      data_test: {},
      rowkey: 842,
      latest_updater: null,
      cache_time: 0,
      internal_hash_row:
        "23be75f166d4658d64761684e77c5b8f18f8ff87eae81582aa510c8ec14a79c5",
    },
    {
      endpoint: "/api/demo/main/test_soap/0.02/dev",
      idendpoint: "2c275d34-f052-46db-b04c-be8ccf298954",
      enabled: true,
      access: 0,
      ctrl: null,
      environment: "dev",
      resource: "/main/test_soap/0.02",
      method: "GET",
      handler: "SOAP",
      cors: null,
      code: '"$_VAR_SOAP_TEST"',
      description: "",
      headers_test: {},
      data_test: {},
      rowkey: 531,
      latest_updater: null,
      cache_time: 0,
      internal_hash_row:
        "dfe319f1eb94d9a686ee9fc3ed239c35bc7ab8f64a5f726a09ecb9fb1d8812a6",
    },
    {
      endpoint: "/api/demo/main/test_soap/full_functions/dev",
      idendpoint: "fa9f500c-2687-46ab-9e3b-948a7c2340fa",
      enabled: true,
      access: 0,
      ctrl: null,
      environment: "dev",
      resource: "/main/test_soap/full_functions",
      method: "POST",
      handler: "SOAP",
      cors: null,
      code: '{\n  "wsdl": "https://www.dataaccess.com/webservicesserver/numberconversion.wso?WSDL",\n  "BasicAuthSecurity": {\n    "User": "any",\n    "Password": "any"\n  }\n}',
      description: "",
      headers_test: {},
      data_test: {},
      rowkey: 723,
      latest_updater: null,
      cache_time: 0,
      internal_hash_row:
        "0f5e49e04009c8bde4f1bb94756b2d386cc2e4a14a8c5833163acf59d3bf48e8",
    },
    {
      endpoint: "/api/demo/main/test_sql/0.02/dev",
      idendpoint: "9d103a43-1463-4b6f-9acf-13570990f976",
      enabled: true,
      access: 0,
      ctrl: null,
      environment: "dev",
      resource: "/main/test_sql/0.02",
      method: "GET",
      handler: "SQL",
      cors: null,
      code: '{\n  "config": {\n    "database": "memory",\n    "username": "",\n    "password": "",\n    "options": {\n      "host": "localhost",\n      "dialect": "sqlite"\n    }\n  },\n  "query": "SELECT $name as nombre;"\n}',
      description: "",
      headers_test: {},
      data_test: {
        body: {
          js: {},
          xml: {},
          text: {},
          selection: 0,
        },
        auth: {
          basic: {},
          bearer: {},
          selection: 0,
        },
        query: [
          {
            enabled: true,
            key: "name",
            value: "edwin",
            internal_hash_row:
              "9ccfc81b3fa34f06ef9d3e43d5c5d0ac2ecbb4f14fd4eca71a715f9f1b1fa551",
          },
        ],
        headers: [
          {
            enabled: false,
            key: "",
            value: "",
            internal_hash_row:
              "c5c647b00670bea65a11ab75bf3c77407cc89d1e12a5a013b5fa8146d30f9368",
          },
        ],
      },
      rowkey: 947,
      latest_updater: null,
      cache_time: 0,
      internal_hash_row:
        "fa605bddd22ded9641c5116499313cc5c81aa5261761da10f45d51141184e0b0",
    },
    {
      endpoint: "/api/demo/main/test_sql/0.03/dev",
      idendpoint: "6609b44a-9e8f-4939-af04-b7c9c2f4d731",
      enabled: true,
      access: 0,
      ctrl: null,
      environment: "dev",
      resource: "/main/test_sql/0.03",
      method: "GET",
      handler: "SQL",
      cors: null,
      code: '{"config": {"database": "memory",\n  "username": "",\n  "password": "",\n  "options": {\n    "host": "localhost",\n    "dialect": "sqlite"\n  }},  "query": "SELECT 1097 AS test_sql;"\n}',
      description: "",
      headers_test: {},
      data_test: {},
      rowkey: 689,
      latest_updater: null,
      cache_time: 0,
      internal_hash_row:
        "f15b21e241dc7f4e6aebe43211f5c1e9906a1a6d6e5bbae2deb364b5a130b761",
    },
    {
      endpoint: "/api/demo/main/test_sql/0.04/dev",
      idendpoint: "a9a7664e-07dc-4f5d-b126-55a46f713eea",
      enabled: true,
      access: 0,
      ctrl: null,
      environment: "dev",
      resource: "/main/test_sql/0.04",
      method: "GET",
      handler: "SQL",
      cors: null,
      code: '{"config": { "database": "msdb",\n  "username": "sa",\n  "password": "sqlkarma",\n  "options": {\n    "host": "192.168.138.30",\n    "dialect": "mssql",\n    "encrypt": false\n  }}, "query": "SELECT\\n    job_id AS [Job ID],\\n    name AS [Job Name],\\n    enabled AS [Is Enabled]\\nFROM\\n    msdb.dbo.sysjobs;"\n}',
      description: "",
      headers_test: {},
      data_test: {},
      rowkey: 688,
      latest_updater: null,
      cache_time: 0,
      internal_hash_row:
        "14d0c8dc3eb8e744d007e88b028fe1cad9f6680dd77b32907e6d6309cecfead8",
    },
    {
      endpoint: "/api/demo/main/test_sql/0.05/dev",
      idendpoint: "66caf48c-19bd-4262-8d03-64bcc00e94f6",
      enabled: true,
      access: 0,
      ctrl: null,
      environment: "dev",
      resource: "/main/test_sql/0.05",
      method: "GET",
      handler: "SQL",
      cors: null,
      code: '{\n  "config": "$_VAR_SQLITE",\n  "query": "SELECT $name as nombre, strftime(\'%Y-%m-%d %H-%M-%S\',\'now\') AS dt;"\n}',
      description: "",
      headers_test: {},
      data_test: {},
      rowkey: 144,
      latest_updater: null,
      cache_time: 0,
      internal_hash_row:
        "eee9731a3b9aa9da92ccf2a0fefbb3e9fe72afcb8688342e1ab9db9b407f2709",
    },
    {
      endpoint: "/ws/demo/main/test_ws/0.01/dev",
      idendpoint: "a3039116-15e7-4e3b-b373-68700e3a9558",
      enabled: true,
      access: 2,
      ctrl: null,
      environment: "dev",
      resource: "/main/test_ws/0.01",
      method: "WS",
      handler: "NA",
      cors: null,
      code: '{"userAuthentication":false,"tokenAuthentication":false,"broadcast":true}',
      description: "",
      headers_test: {},
      data_test: {},
      rowkey: 231,
      latest_updater: null,
      cache_time: 0,
      internal_hash_row:
        "4ee69a429636e2d012c3edc7897796fcf0a87275f8361f2056410d8ac54309cb",
    },
    {
      endpoint: "/ws/demo/main/test_ws/0.02/dev",
      idendpoint: "fa9e68a8-ca71-410a-8507-4009a23da6c9",
      enabled: true,
      access: 0,
      ctrl: null,
      environment: "dev",
      resource: "/main/test_ws/0.02",
      method: "WS",
      handler: "NA",
      cors: null,
      code: '{"userAuthentication":true,"tokenAuthentication":false,"broadcast":false}',
      description: "",
      headers_test: {},
      data_test: {},
      rowkey: 672,
      latest_updater: null,
      cache_time: 0,
      internal_hash_row:
        "f4ad919cfbb2c69081e9e57119a6fcce74e67ade9f060ceb5d39e38271770513",
    },
    {
      endpoint: "/ws/demo/main/test_ws/0.03/dev",
      idendpoint: "6916abfb-7b96-423c-88ca-db99c56657d6",
      enabled: true,
      access: 2,
      ctrl: null,
      environment: "dev",
      resource: "/main/test_ws/0.03",
      method: "WS",
      handler: "NA",
      cors: null,
      code: '{"userAuthentication":false,"tokenAuthentication":true,"broadcast":false}',
      description: "",
      headers_test: {},
      data_test: {},
      rowkey: 56,
      latest_updater: null,
      cache_time: 0,
      internal_hash_row:
        "6cf6bd47fe45cc250239a7270324fcc7a012ff80328135e8f47474d99cd9b862",
    },
  ],
};
