export const system_app = {
  vars: {
    dev: {},
    qa: {},
    prd: {},
  },
  params: {
    users: [],
    telegram: {
      idgroup: "",
    },
  },
  idapp: "cfcd2084-95d5-65ef-66e7-dff9f98764da",
  app: "system",
  enabled: true,
  description: "App System",
  rowkey: 0,
  endpoints: [
    {
      enabled: true,
      endpoint: "/ws/system/websocket/app/info/prd",
      method: "WS",
      handler: "NA",
      mcp: {},
      access: 0,
      cache_time: 0,
      ctrl: {},
      resource: "/websocket/app/info",
      code: "fnGetCacheSize",
      rowkey: 121,
      description: "Send events from apps.",
      idendpoint: "a0130d77-b779-4dea-a87f-6841520ffade",
      cors: {},
      headers_test: {},
      data_test: {
        query: [
          {
            enabled: false,
            key: "",
            value: "",
            internal_hash_row:
              "c5c647b00670bea65a11ab75bf3c77407cc89d1e12a5a013b5fa8146d30f9368",
          },
        ],
        body: {
          selection: 0,
          json: {
            code: {},
          },
          xml: {
            code: "",
          },
          text: {
            value: "",
          },
          form: {},
        },
        headers: [
          {
            enabled: false,
            key: "",
            value: "",
            internal_hash_row:
              "c5c647b00670bea65a11ab75bf3c77407cc89d1e12a5a013b5fa8146d30f9368",
          },
        ],
        auth: {
          basic: {
            username: "",
            password: "",
          },
          bearer: {
            token: "",
          },
          selection: 0,
        },
      },
      latest_updater: null,
      environment: "prd",
      json_schema: {
        in: {
          enabled: false,
          schema: {
            type: "object",
            properties: {},
            additionalProperties: true,
          },
        },
        out: {
          enabled: false,
          schema: {
            type: "object",
            properties: {},
            additionalProperties: true,
          },
        },
      },
      internal_hash_row:
        "8b9529f7686ed4f777c64a10bfff544df9f6b19b2c87c8fd611c10025f54759a",
    },
    {
      enabled: true,
      endpoint: "/api/system/api/handler/documentation/prd",
      method: "GET",
      handler: "FUNCTION",
      mcp: {},
      access: 0,
      cache_time: 3600,
      ctrl: {},
      resource: "/api/handler/documentation",
      code: "fnGetHandlerDocs",
      rowkey: 83,
      description: "Get documentation of a specific handler",
      idendpoint: "25ca7819-8823-4835-87c5-04b792bc594d",
      cors: {},
      headers_test: {},
      data_test: {},
      latest_updater: null,
      environment: "prd",
      json_schema: {
        in: {
          enabled: false,
          schema: {
            type: "object",
            properties: {},
            additionalProperties: true,
          },
        },
        out: {
          enabled: false,
          schema: {
            type: "object",
            properties: {},
            additionalProperties: true,
          },
        },
      },
      internal_hash_row:
        "f5eb3df20ecd0c23ae716b7a4d51ab1638591f1214608027c208858609328913",
    },
    {
      enabled: true,
      endpoint: "/api/system/interval_tasks/byidapp/prd",
      method: "GET",
      handler: "FUNCTION",
      mcp: {},
      access: 0,
      cache_time: 0,
      ctrl: {},
      resource: "/interval_tasks/byidapp",
      code: "fnGetIntervalTasksByIdApp",
      rowkey: 558,
      description: "",
      idendpoint: "71cfbad5-cf5f-4d64-a952-1a52af0bf26b",
      cors: {},
      headers_test: {},
      data_test: {
        query: [
          {
            enabled: false,
            key: "",
            value: "",
            internal_hash_row:
              "c5c647b00670bea65a11ab75bf3c77407cc89d1e12a5a013b5fa8146d30f9368",
          },
        ],
        body: {
          selection: 0,
          json: {
            code: {},
          },
          xml: {
            code: "",
          },
          text: {
            value: "",
          },
          form: {},
        },
        headers: [
          {
            enabled: false,
            key: "",
            value: "",
            internal_hash_row:
              "c5c647b00670bea65a11ab75bf3c77407cc89d1e12a5a013b5fa8146d30f9368",
          },
        ],
        auth: {
          basic: {
            username: "",
            password: "",
          },
          bearer: {
            token: "",
          },
          selection: 0,
        },
      },
      latest_updater: null,
      environment: "prd",
      json_schema: {},
      internal_hash_row:
        "12506f5aab506eb32143aa1c9bff393948b2bbea2e9868afb899d5912e83ddbe",
    },
    {
      enabled: true,
      endpoint: "/api/system/api/token/0.01/prd",
      method: "POST",
      handler: "FUNCTION",
      mcp: {},
      access: 0,
      cache_time: 0,
      ctrl: {
        admin: true,
      },
      resource: "/api/token/0.01",
      code: "fnToken",
      rowkey: 19,
      description: "",
      idendpoint: "15ca7819-8823-4835-87c5-04b792bc594d",
      cors: {},
      headers_test: {},
      data_test: {},
      latest_updater: null,
      environment: "prd",
      json_schema: {},
      internal_hash_row:
        "721cadf02b392dc09578d6049ab8bb6966267f0dc64cd323c6ec271a33d43eb2",
    },
    {
      enabled: true,
      endpoint: "/api/system/api/app/0.01/qa",
      method: "GET",
      handler: "FUNCTION",
      mcp: {},
      access: 2,
      cache_time: 0,
      ctrl: {
        admin: true,
      },
      resource: "/api/app/0.01",
      code: "fnGetAppById",
      rowkey: 978,
      description: "",
      idendpoint: "9dcc9e25-1238-411e-87f8-78f318455c7e",
      cors: {},
      headers_test: {},
      data_test: {},
      latest_updater: null,
      environment: "qa",
      json_schema: {},
      internal_hash_row:
        "a92c022a8e0db6a29c1344c27144b3442421fc87cd7aae6012836c18aa86c736",
    },
    {
      enabled: true,
      endpoint: "/api/system/api/token/0.01/qa",
      method: "POST",
      handler: "FUNCTION",
      mcp: {},
      access: 0,
      cache_time: 0,
      ctrl: {
        admin: true,
      },
      resource: "/api/token/0.01",
      code: "fnToken",
      rowkey: 879,
      description: "",
      idendpoint: "65cdde4c-8000-4248-bd77-157257b6d9c2",
      cors: {},
      headers_test: {},
      data_test: {},
      latest_updater: null,
      environment: "qa",
      json_schema: {},
      internal_hash_row:
        "0ee632dc414b52da68445791ecff28484a59f2bc33013900fc4c529ee67fa45e",
    },
    {
      enabled: true,
      endpoint: "/api/system/system/environment/0.01/prd",
      method: "GET",
      handler: "FUNCTION",
      mcp: {},
      access: 2,
      cache_time: 0,
      ctrl: {
        admin: true,
      },
      resource: "/system/environment/0.01",
      code: "fnGetEnvironment",
      rowkey: 605,
      description: "",
      idendpoint: "d7737d40-5cd8-45f2-a60a-1014272a2faf",
      cors: {},
      headers_test: {},
      data_test: {},
      latest_updater: null,
      environment: "prd",
      json_schema: {},
      internal_hash_row:
        "8ef82abd1ba18ed3a4eade72d8feff388076dbe05ef8cb6eac3650d53a4f4274",
    },
    {
      enabled: true,
      endpoint: "/ws/system/websocket/hooks/prd",
      method: "WS",
      handler: "NA",
      mcp: {},
      access: 0,
      cache_time: 0,
      ctrl: {
        admin: true,
      },
      resource: "/websocket/hooks",
      code: "",
      rowkey: 378,
      description: "",
      idendpoint: "3eb8b6c8-e001-43e6-9ace-517a05d33e6b",
      cors: {},
      headers_test: {},
      data_test: {},
      latest_updater: null,
      environment: "prd",
      json_schema: {},
      internal_hash_row:
        "c36d84ac720a0f856fa7c59c005cfde882af500ccfe0326a1edab5438a8b849f",
    },
    {
      enabled: true,
      endpoint: "/api/system/system/login/0.01/prd",
      method: "POST",
      handler: "FUNCTION",
      mcp: {},
      access: 0,
      cache_time: 0,
      ctrl: {
        admin: true,
      },
      resource: "/system/login/0.01",
      code: "fnLogin",
      rowkey: 264,
      description: "",
      idendpoint: "871cd2ed-8456-4e5e-8ab5-b7724a908191",
      cors: {},
      headers_test: {},
      data_test: {},
      latest_updater: null,
      environment: "prd",
      json_schema: {},
      internal_hash_row:
        "229c69578fde3b75869d3abd1413daa47109fefd9af709dec099c9937cc007c0",
    },
    {
      enabled: true,
      endpoint: "/api/system/api/apps/0.01/dev",
      method: "GET",
      handler: "FUNCTION",
      mcp: {},
      access: 2,
      cache_time: 0,
      ctrl: {
        admin: true,
      },
      resource: "/api/apps/0.01",
      code: "fnGetApps",
      rowkey: 395,
      description: "",
      idendpoint: "48f6c75d-285c-420d-b6d7-9471bf052c1e",
      cors: {},
      headers_test: {},
      data_test: {},
      latest_updater: null,
      environment: "dev",
      json_schema: {},
      internal_hash_row:
        "87e092add1bc6a8aa4fc93f411ef65d059f0447042a04384e68c5416b6b7129b",
    },
    {
      enabled: true,
      endpoint: "/api/system/api/apps/0.01/qa",
      method: "GET",
      handler: "FUNCTION",
      mcp: {},
      access: 2,
      cache_time: 0,
      ctrl: {
        admin: true,
      },
      resource: "/api/apps/0.01",
      code: "fnGetApps",
      rowkey: 533,
      description: "",
      idendpoint: "dae4d3ff-6782-4fd3-8837-d169cf1aded8",
      cors: {},
      headers_test: {},
      data_test: {},
      latest_updater: null,
      environment: "qa",
      json_schema: {},
      internal_hash_row:
        "e2da56d382734c9462fa7d563fcc4e63d5b531edb5a9109b50c3889cae0e414f",
    },
    {
      enabled: true,
      endpoint: "/api/system/api/app/0.01/prd",
      method: "GET",
      handler: "FUNCTION",
      mcp: {},
      access: 2,
      cache_time: 0,
      ctrl: {
        admin: true,
      },
      resource: "/api/app/0.01",
      code: "fnGetAppById",
      rowkey: 996,
      description: "",
      idendpoint: "15034cf9-4c94-43ba-bc7a-3d762f62d7de",
      cors: {},
      headers_test: {},
      data_test: {},
      latest_updater: null,
      environment: "prd",
      json_schema: {},
      internal_hash_row:
        "08d8b2500aa846ad635c0827e1114ffdc2200a0401573afe3ae24166c19bbdb9",
    },
    {
      enabled: true,
      endpoint: "/api/system/system/token/api/prd",
      method: "POST",
      handler: "FUNCTION",
      mcp: {},
      access: 0,
      cache_time: 0,
      ctrl: {
        admin: true,
      },
      resource: "/system/token/api",
      code: "fnToken",
      rowkey: 573,
      description: "",
      idendpoint: "b5141492-3ad1-4ea6-a85d-ceb23ba26244",
      cors: {},
      headers_test: {},
      data_test: {},
      latest_updater: null,
      environment: "prd",
      json_schema: {},
      internal_hash_row:
        "a4c47c874e5deecde6a6e83be9a31b48113e7cef8c3adfb4596556600e349c5a",
    },
    {
      enabled: true,
      endpoint: "/api/system/cache/response/size/prd",
      method: "GET",
      handler: "FUNCTION",
      mcp: {},
      access: 0,
      cache_time: 0,
      ctrl: {},
      resource: "/cache/response/size",
      code: "fnGetCacheSize",
      rowkey: 609,
      description: "",
      idendpoint: "047845ac-5367-48ed-9465-8e36ba6c7bae",
      cors: {},
      headers_test: {},
      data_test: {},
      latest_updater: null,
      environment: "prd",
      json_schema: {},
      internal_hash_row:
        "e780e63834198691f678a769643c57c923cb827748256cbb965aff032c2ec02f",
    },
    {
      enabled: true,
      endpoint: "/api/system/cache/clear/prd",
      method: "POST",
      handler: "FUNCTION",
      mcp: {},
      access: 0,
      cache_time: 0,
      ctrl: {},
      resource: "/cache/clear",
      code: "fnClearCache",
      rowkey: 64,
      description: "",
      idendpoint: "3ead2170-283d-4c6a-abc1-eddd217b6d01",
      cors: {},
      headers_test: {},
      data_test: {},
      latest_updater: null,
      environment: "prd",
      json_schema: {},
      internal_hash_row:
        "7439d230417ac1c30e62b4583982cfb382bcf93ee008aef9da4a63d981e752f7",
    },
    {
      enabled: true,
      endpoint: "/api/system/system/log/prd",
      method: "GET",
      handler: "FUNCTION",
      mcp: {},
      access: 0,
      cache_time: 60,
      ctrl: {
        users: [],
        log: {
          level: 0,
        },
      },
      resource: "/system/log",
      code: "fnGetLogs",
      rowkey: 154,
      description: "",
      idendpoint: "c10b1812-8b25-4b16-adb9-bf7ac8134f76",
      cors: {},
      headers_test: {},
      data_test: {
        body: {
          json: {
            code: "",
          },
          xml: {
            code: "",
          },
          text: {},
          selection: 0,
        },
        auth: {
          basic: {},
          bearer: {},
          selection: 0,
        },
        headers: [
          {
            enabled: true,
            key: "",
            value: "",
            internal_hash_row:
              "b9427bedda283d6b3c25ad634983b8bfbfc32d5a3006a5a9d6c541a332f1d983",
          },
        ],
        query: [
          {
            enabled: true,
            key: "",
            value: "",
            internal_hash_row:
              "b9427bedda283d6b3c25ad634983b8bfbfc32d5a3006a5a9d6c541a332f1d983",
          },
        ],
      },
      latest_updater: null,
      environment: "prd",
      json_schema: {},
      internal_hash_row:
        "3040a41065e69cb4c84d246617a1ee19d742d3b7a79a8e8b955efef1df6f136f",
    },
    {
      enabled: true,
      endpoint: "/api/system/api/function_names/prd",
      method: "GET",
      handler: "FUNCTION",
      mcp: {},
      access: 0,
      cache_time: 999,
      ctrl: {
        users: [],
        log: {},
      },
      resource: "/api/function_names",
      code: "fnFunctionNames",
      rowkey: 218,
      description: "",
      idendpoint: "13f94d7d-6612-4c30-8202-286cbbe3da3e",
      cors: {},
      headers_test: {},
      data_test: {
        query: [
          {
            enabled: true,
            key: "env",
            value: "prd",
            internal_hash_row:
              "c5c647b00670bea65a11ab75bf3c77407cc89d1e12a5a013b5fa8146d30f9368",
          },
        ],
        body: {
          selection: 0,
          json: {
            code: {},
          },
          xml: {
            code: "",
          },
          text: {
            value: "",
          },
          form: {},
        },
        headers: [
          {
            enabled: false,
            key: "",
            value: "",
            internal_hash_row:
              "c5c647b00670bea65a11ab75bf3c77407cc89d1e12a5a013b5fa8146d30f9368",
          },
        ],
        auth: {
          basic: {
            username: "",
            password: "",
          },
          bearer: {
            token: "",
          },
          selection: 0,
        },
      },
      latest_updater: null,
      environment: "prd",
      json_schema: {},
      internal_hash_row:
        "093807b03d81722072af36ac38a8bb43fa12789739b12c6a1f4e8610be8eebc3",
    },
    {
      enabled: true,
      endpoint: "/api/system/interval_tasks/upsert/prd",
      method: "POST",
      handler: "FUNCTION",
      mcp: {},
      access: 0,
      cache_time: 0,
      ctrl: {},
      resource: "/interval_tasks/upsert",
      code: "fnUpsertIntervalTask",
      rowkey: 562,
      description: "",
      idendpoint: "34987a43-63e4-4926-824b-5254155b5c80",
      cors: {},
      headers_test: {},
      data_test: {
        query: [
          {
            enabled: false,
            key: "",
            value: "",
            internal_hash_row:
              "c5c647b00670bea65a11ab75bf3c77407cc89d1e12a5a013b5fa8146d30f9368",
          },
        ],
        body: {
          selection: 0,
          json: {
            code: {},
          },
          xml: {
            code: "",
          },
          text: {
            value: "",
          },
          form: {},
        },
        headers: [
          {
            enabled: false,
            key: "",
            value: "",
            internal_hash_row:
              "c5c647b00670bea65a11ab75bf3c77407cc89d1e12a5a013b5fa8146d30f9368",
          },
        ],
        auth: {
          basic: {
            username: "",
            password: "",
          },
          bearer: {
            token: "",
          },
          selection: 0,
        },
      },
      latest_updater: null,
      environment: "prd",
      json_schema: {},
      internal_hash_row:
        "aedb96b3a42e07dea01678726b07a48d159138679b9a7f1308743cfbafc544f6",
    },
    {
      enabled: true,
      endpoint: "/api/system/system/logout/0.01/prd",
      method: "POST",
      handler: "FUNCTION",
      mcp: {},
      access: 2,
      cache_time: 0,
      ctrl: {
        admin: true,
      },
      resource: "/system/logout/0.01",
      code: "fnLogout",
      rowkey: 787,
      description: "",
      idendpoint: "131cca3e-f835-4414-89ca-5ddbbec5ab89",
      cors: {},
      headers_test: {},
      data_test: {},
      latest_updater: null,
      environment: "prd",
      json_schema: {},
      internal_hash_row:
        "dc50c1e06de2c5b442a6997c9b9e8fe2d61862a8ad5909e01a8ef7da8439e4df",
    },
    {
      enabled: true,
      endpoint: "/api/system/system/log/prd",
      method: "POST",
      handler: "FUNCTION",
      mcp: {},
      access: 0,
      cache_time: 0,
      ctrl: {
        users: [],
        log: {},
      },
      resource: "/system/log",
      code: "fnInsertLog",
      rowkey: 895,
      description: "",
      idendpoint: "18731c87-9d59-44b6-8871-ecaa493008e5",
      cors: {},
      headers_test: {},
      data_test: {
        body: {
          js: {
            code: "{}",
          },
          xml: {
            code: "",
          },
          text: {},
          selection: 0,
        },
        auth: {
          basic: {},
          bearer: {},
          selection: 0,
        },
        headers: [
          {
            enabled: true,
            key: "",
            value: "",
            internal_hash_row:
              "b9427bedda283d6b3c25ad634983b8bfbfc32d5a3006a5a9d6c541a332f1d983",
          },
        ],
        query: [
          {
            enabled: true,
            key: "",
            value: "",
            internal_hash_row:
              "b9427bedda283d6b3c25ad634983b8bfbfc32d5a3006a5a9d6c541a332f1d983",
          },
        ],
      },
      latest_updater: null,
      environment: "prd",
      json_schema: {},
      internal_hash_row:
        "5d3d6ff54bac5dc0ab1bc637b0aabaa7c8425587c264affe702656f801814cf0",
    },
    {
      enabled: true,
      endpoint: "/api/system/api/app/0.01/qa",
      method: "POST",
      handler: "FUNCTION",
      mcp: {},
      access: 2,
      cache_time: 0,
      ctrl: {
        admin: true,
      },
      resource: "/api/app/0.01",
      code: "fnSaveApp",
      rowkey: 723,
      description: "",
      idendpoint: "6f1358ae-a638-47f8-a5d1-57818f17426b",
      cors: {},
      headers_test: {},
      data_test: {},
      latest_updater: null,
      environment: "qa",
      json_schema: {},
      internal_hash_row:
        "06bf6d29b4a1ae822e3ee9f7875ec3ce9a78d699b051b666508c3883d81cef2b",
    },
    {
      enabled: true,
      endpoint: "/api/system/api/app/0.01/prd",
      method: "POST",
      handler: "FUNCTION",
      mcp: {},
      access: 2,
      cache_time: 0,
      ctrl: {
        admin: true,
      },
      resource: "/api/app/0.01",
      code: "fnSaveApp",
      rowkey: 849,
      description: "",
      idendpoint: "d9086725-367f-4383-8b43-c23071bc8fcc",
      cors: {},
      headers_test: {},
      data_test: {},
      latest_updater: null,
      environment: "prd",
      json_schema: {},
      internal_hash_row:
        "68df1f03c77ec318b17402c40c1e62d1403168157de2aa55f86fe1e342bebe60",
    },
    {
      enabled: true,
      endpoint: "/api/system/api/token/0.01/dev",
      method: "POST",
      handler: "FUNCTION",
      mcp: {},
      access: 0,
      cache_time: 0,
      ctrl: {
        admin: true,
      },
      resource: "/api/token/0.01",
      code: "fnToken",
      rowkey: 3,
      description: "",
      idendpoint: "52fb738c-7d1f-4eba-afb4-508a9fa9d06a",
      cors: {},
      headers_test: {},
      data_test: {},
      latest_updater: null,
      environment: "dev",
      json_schema: {},
      internal_hash_row:
        "8e4ab65dafbabbc52677b4c810b8dd9effe2ec02661d5c1b79c08913fbd4ffad",
    },
    {
      enabled: true,
      endpoint: "/api/system/database/hooks/prd",
      method: "POST",
      handler: "JS",
      mcp: {},
      access: 0,
      cache_time: 0,
      ctrl: {
        users: [],
        log: {
          status_info: 1,
          status_success: 1,
          status_redirect: 1,
          status_client_error: 2,
          status_server_error: 3,
        },
      },
      resource: "/database/hooks",
      code: "$_SERVER_.checkwebHookDB($_REQUEST_);\n",
      rowkey: 807,
      description:
        "Receiver of hooks issued from the database, these events will be forwarded via websocket to be consumed by clients.",
      idendpoint: "2cf4eecc-1bbe-433a-b8eb-347a7de52d4d",
      cors: {},
      headers_test: {},
      data_test: {
        query: [
          {
            enabled: false,
            key: "",
            value: "",
            internal_hash_row:
              "c5c647b00670bea65a11ab75bf3c77407cc89d1e12a5a013b5fa8146d30f9368",
          },
        ],
        body: {
          selection: 0,
          json: {
            code: {},
          },
          xml: {
            code: "",
          },
          text: {
            value: "",
          },
          form: {},
        },
        headers: [
          {
            enabled: false,
            key: "",
            value: "",
            internal_hash_row:
              "c5c647b00670bea65a11ab75bf3c77407cc89d1e12a5a013b5fa8146d30f9368",
          },
        ],
        auth: {
          basic: {
            username: "",
            password: "",
          },
          bearer: {
            token: "",
          },
          selection: 0,
        },
      },
      latest_updater: null,
      environment: "prd",
      json_schema: {},
      internal_hash_row:
        "95b2a10e249e8fc835d8b560376ec5f3e41efe3fe822624dbb9015a56370b9ce",
    },
    {
      enabled: true,
      endpoint: "/api/system/api/telegram/sendphoto/prd",
      method: "POST",
      handler: "FUNCTION",
      mcp: {},
      access: 0,
      cache_time: 0,
      ctrl: {
        users: [],
        log: {},
      },
      resource: "/api/telegram/sendphoto",
      code: "fnTelegramsendPhoto",
      rowkey: 656,
      description: "",
      idendpoint: "db9cff16-81b8-438e-b5fb-6ceb4d6a0a60",
      cors: {},
      headers_test: {},
      data_test: {
        query: [
          {
            enabled: false,
            key: "",
            value: "",
            internal_hash_row:
              "c5c647b00670bea65a11ab75bf3c77407cc89d1e12a5a013b5fa8146d30f9368",
          },
        ],
        body: {
          selection: 0,
          json: {
            code: {
              chatId: -1001790805365,
              url_photo:
                "https://www.demo.com/wp-content/uploads/2024/11/MAPA1.jpg",
              extra: {
                message_thread_id: 16964,
                parse_mode: "MarkdownV2",
                caption: "Farma Foto",
              },
              autoscape: false,
            },
          },
          xml: {
            code: "",
          },
          text: {
            value: "",
          },
          form: {},
        },
        headers: [
          {
            enabled: false,
            key: "",
            value: "",
            internal_hash_row:
              "c5c647b00670bea65a11ab75bf3c77407cc89d1e12a5a013b5fa8146d30f9368",
          },
        ],
        auth: {
          basic: {
            username: "",
            password: "",
          },
          bearer: {
            token: "",
          },
          selection: 0,
        },
      },
      latest_updater: null,
      environment: "prd",
      json_schema: {},
      internal_hash_row:
        "5716d720aa0ae28fdbb625fe40c931e21acf0b725d81cd4f08ef03e454e458bc",
    },
    {
      enabled: true,
      endpoint: "/api/system/system/method/0.01/prd",
      method: "GET",
      handler: "FUNCTION",
      mcp: {},
      access: 2,
      cache_time: 0,
      ctrl: {
        admin: true,
      },
      resource: "/system/method/0.01",
      code: "fnGetMethod",
      rowkey: 773,
      description: "",
      idendpoint: "0144753a-61a6-4ee1-8ae5-1d871dd21d24",
      cors: {},
      headers_test: {},
      data_test: {},
      latest_updater: null,
      environment: "prd",
      json_schema: {},
      internal_hash_row:
        "4587dc39b916c1a3d2791774f41dfff75c7139b272a9ec204d33dca5f285dd92",
    },
    {
      enabled: true,
      endpoint: "/api/system/api/apps/0.01/prd",
      method: "GET",
      handler: "FUNCTION",
      mcp: {},
      access: 2,
      cache_time: 0,
      ctrl: {
        admin: true,
      },
      resource: "/api/apps/0.01",
      code: "fnGetApps",
      rowkey: 111,
      description: "",
      idendpoint: "55bdde78-051e-4844-a4b2-089f122f616e",
      cors: {},
      headers_test: {},
      data_test: {},
      latest_updater: null,
      environment: "prd",
      json_schema: {},
      internal_hash_row:
        "ee4c0c6dd4ae4b60eab98c7dc941fecd55e70c02d1efa903236f08df0126e18f",
    },
    {
      enabled: true,
      endpoint: "/api/system/api/telegram/sendmsg/prd",
      method: "POST",
      handler: "FUNCTION",
      mcp: {},
      access: 0,
      cache_time: 0,
      ctrl: {
        users: [],
        log: {
          infor: true,
          success: true,
          redirection: true,
          clientError: true,
          serverError: true,
          full: true,
        },
      },
      resource: "/api/telegram/sendmsg",
      code: "fnTelegramsendMessage",
      rowkey: 36,
      description: "",
      idendpoint: "9c4c5630-f1da-4885-b845-7b2e03eab215",
      cors: {},
      headers_test: {},
      data_test: {
        body: {
          json: {
            code: {
              chatId: -1001790805365,
              message: "*bold \\*text*",
              extra: {
                message_thread_id: 16964,
                parse_mode: "MarkdownV2",
              },
              autoscape: false,
            },
          },
          xml: {
            code: "",
          },
          text: {},
          selection: 0,
          form: {},
        },
        auth: {
          basic: {},
          bearer: {},
          selection: 0,
        },
        headers: [
          {
            enabled: true,
            key: "",
            value: "",
            internal_hash_row:
              "b9427bedda283d6b3c25ad634983b8bfbfc32d5a3006a5a9d6c541a332f1d983",
          },
        ],
        query: [
          {
            enabled: true,
            key: "",
            value: "",
            internal_hash_row:
              "b9427bedda283d6b3c25ad634983b8bfbfc32d5a3006a5a9d6c541a332f1d983",
          },
        ],
      },
      latest_updater: null,
      environment: "prd",
      json_schema: {},
      internal_hash_row:
        "e95cfcbb209a51b4c80e49d08521d154c5af43730e2184884c3b98d71e683263",
    },
    {
      enabled: true,
      endpoint: "/api/system/api/app/0.01/dev",
      method: "POST",
      handler: "FUNCTION",
      mcp: {},
      access: 2,
      cache_time: 0,
      ctrl: {
        admin: true,
      },
      resource: "/api/app/0.01",
      code: "fnSaveApp",
      rowkey: 555,
      description: "",
      idendpoint: "bc07e60d-d608-4763-b712-8ae01156fea7",
      cors: {},
      headers_test: {},
      data_test: {},
      latest_updater: null,
      environment: "dev",
      json_schema: {},
      internal_hash_row:
        "6a3df35f6867183f32aa8312cabd0f3e501c9b365bc7e4ced24d2086b8c798a8",
    },
    {
      enabled: true,
      endpoint: "/api/system/api/app/0.01/dev",
      method: "GET",
      handler: "FUNCTION",
      mcp: {},
      access: 2,
      cache_time: 0,
      ctrl: {
        admin: true,
      },
      resource: "/api/app/0.01",
      code: "fnGetAppById",
      rowkey: 352,
      description: "",
      idendpoint: "82a678a2-04ef-4231-8091-7ea3432515f4",
      cors: {},
      headers_test: {},
      data_test: {},
      latest_updater: null,
      environment: "dev",
      json_schema: {},
      internal_hash_row:
        "69db5d106ffc47462dbdf9910f3001c365713d435ae5435beb8319828052a4a4",
    },
    {
      enabled: true,
      endpoint: "/api/system/interval_tasks/delete/prd",
      method: "DELETE",
      handler: "FUNCTION",
      mcp: {},
      access: 0,
      cache_time: 0,
      ctrl: {},
      resource: "/interval_tasks/delete",
      code: "fndeleteIntervalTask",
      rowkey: 152,
      description: "",
      idendpoint: "e753e2db-ca20-4607-82b7-34b70e435a0c",
      cors: {},
      headers_test: {},
      data_test: {
        query: [
          {
            enabled: false,
            key: "",
            value: "",
            internal_hash_row:
              "c5c647b00670bea65a11ab75bf3c77407cc89d1e12a5a013b5fa8146d30f9368",
          },
        ],
        body: {
          selection: 0,
          json: {
            code: {},
          },
          xml: {
            code: "",
          },
          text: {
            value: "",
          },
          form: {},
        },
        headers: [
          {
            enabled: false,
            key: "",
            value: "",
            internal_hash_row:
              "c5c647b00670bea65a11ab75bf3c77407cc89d1e12a5a013b5fa8146d30f9368",
          },
        ],
        auth: {
          basic: {
            username: "",
            password: "",
          },
          bearer: {
            token: "",
          },
          selection: 0,
        },
      },
      latest_updater: null,
      environment: "prd",
      json_schema: {},
      internal_hash_row:
        "9ab85d2354c1a50ac12136a6f2e2eb9521e97de436df2f016a942ceb8b9bbdd8",
    },
    {
      enabled: true,
      endpoint: "/api/system/system/handler/js/funtions/prd",
      method: "GET",
      handler: "FUNCTION",
      mcp: {},
      access: 0,
      cache_time: 0,
      ctrl: {
        users: [],
        log: {},
      },
      resource: "/system/handler/js/funtions",
      code: "fnListFnVarsHandlerJS",
      rowkey: 922,
      description: "",
      idendpoint: "3d3de358-681d-4b61-98dc-c1663db0c02c",
      cors: {},
      headers_test: {},
      data_test: {
        query: [
          {
            enabled: false,
            key: "",
            value: "",
            internal_hash_row:
              "c5c647b00670bea65a11ab75bf3c77407cc89d1e12a5a013b5fa8146d30f9368",
          },
        ],
        body: {
          selection: 0,
        },
        headers: {},
        auth: {
          selection: 0,
        },
      },
      latest_updater: null,
      environment: "prd",
      json_schema: {},
      internal_hash_row:
        "8ea100aea45850db868d69586d77b4a85c1a8b1e9b701230b1399f854d8be7ad",
    },
    {
      enabled: true,
      endpoint: "/api/system/users/list/prd",
      method: "GET",
      handler: "FUNCTION",
      mcp: {},
      access: 0,
      cache_time: 0,
      ctrl: {},
      resource: "/users/list",
      code: "fnGetUsersList",
      rowkey: 315,
      description: "",
      idendpoint: "2c6d77b7-d8e2-49e2-9c63-a98a873b389c",
      cors: {},
      headers_test: {},
      data_test: {},
      latest_updater: null,
      environment: "prd",
      json_schema: {},
      internal_hash_row:
        "754b6f508100892f2926ff2a7edf319f11c43ecc43be5590900b2d624fa167ec",
    },
    {
      enabled: true,
      endpoint: "/api/system/system/handler/0.01/prd",
      method: "GET",
      handler: "FUNCTION",
      mcp: {},
      access: 2,
      cache_time: 0,
      ctrl: {
        admin: true,
      },
      resource: "/system/handler/0.01",
      code: "fnGetHandler",
      rowkey: 19,
      description: "",
      idendpoint: "17c211d6-8c81-4274-b5c4-604126454ab0",
      cors: {},
      headers_test: {},
      data_test: {},
      latest_updater: null,
      environment: "prd",
      json_schema: {},
      internal_hash_row:
        "402558a638510a6bf28871e658298d89a8e21a67d2e6ce5606211822fe75542f",
    },
    {
      enabled: true,
      endpoint: "/api/system/system/api/token/prd",
      method: "POST",
      handler: "FUNCTION",
      mcp: {},
      access: 0,
      cache_time: 0,
      ctrl: {
        admin: true,
      },
      resource: "/system/api/token",
      code: "fnAPIToken",
      rowkey: 932,
      description: "",
      idendpoint: "89b6d2c3-5d9e-4c18-9221-5f2673c17bb3",
      cors: {},
      headers_test: {},
      data_test: {},
      latest_updater: null,
      environment: "prd",
      json_schema: {},
      internal_hash_row:
        "2f392919aca98d7583517180ff1aac6e87292acee3fccab2ae0b5f57ae6affaf",
    },
    {
      enabled: true,
      endpoint: "/api/system/responses/status_code/count/prd",
      method: "GET",
      handler: "FUNCTION",
      mcp: {},
      access: 0,
      cache_time: 2,
      ctrl: {},
      resource: "/responses/status_code/count",
      code: "fnGetResponseCountStatus",
      rowkey: 290,
      description: "",
      idendpoint: "4c2516ec-d7c4-4783-8ee5-f7dac5b68a91",
      cors: {},
      headers_test: {},
      data_test: {
        body: {
          json: {
            code: "",
          },
          xml: {
            code: "",
          },
          text: {},
          selection: 0,
        },
        auth: {
          basic: {},
          bearer: {},
          selection: 0,
        },
        headers: [
          {
            enabled: true,
            key: "",
            value: "",
            internal_hash_row:
              "b9427bedda283d6b3c25ad634983b8bfbfc32d5a3006a5a9d6c541a332f1d983",
          },
        ],
        query: [
          {
            enabled: true,
            key: "",
            value: "",
            internal_hash_row:
              "b9427bedda283d6b3c25ad634983b8bfbfc32d5a3006a5a9d6c541a332f1d983",
          },
        ],
      },
      latest_updater: null,
      environment: "prd",
      json_schema: {},
      internal_hash_row:
        "c6673b9b8c17c08a923f270036255f95eb3b3264187e1fcf32c6462caf57d8d5",
    },
  ],
  environment: "dev",
};
